name: jk_nickname
version: '${project.version}'
main: jiekie.NicknamePlugin
api-version: '1.20'
authors: [Jiekie]
description: 닉네임 설정 플러그인
commands:
  닉네임:
    description: 닉네임 설정 명령어
    usage: /닉네임
    tab-completer: jiekie.completer.NicknameTabCompleter